name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          config_timezone: Asia/Tokyo
          config_order: habits, reactions, achievements, code, projects, pagespeed, rss, stackoverflow, anilist
          base: metadata
          plugin_habits: yes
          plugin_reactions: yes
          plugin_achievements: yes
          plugin_code: yes
          plugin_projects: yes
          plugin_pagespeed: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 10004647
          plugin_anilist: yes
          plugin_anilist_user: rukDoe
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
