name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stargazers: yes
          plugin_lines: yes
          plugin_topics: yes
          plugin_stars: yes
