name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          config_timezone: Asia/Tokyo
          config_order: habits, reactions, achievements, code, pagespeed, rss, stackoverflow
          base: metadata
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_languages_threshold: 100%
          plugin_reactions: yes
          plugin_achievements: yes
          plugin_code: yes
          plugin_pagespeed: yes
          plugin_rss: yes
          plugin_rss_source: https://doany.io/feed.xml
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
