name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          config_order: languages, stargazers, topics, stars, habits, reactions, sponsorships, achievements, code, projects, pagespeed, rss, stackoverflow, anilist, music
          base: metadata
          plugin_languages: yes
          plugin_stargazers: yes
          plugin_topics: yes
          plugin_stars: yes
          plugin_habits: yes
          plugin_reactions: yes
          plugin_sponsorships: yes
          plugin_achievements: yes
          plugin_code: yes
          plugin_projects: yes
          plugin_pagespeed: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 10004647
          plugin_anilist: yes
          plugin_anilist_user: rukDoe
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_rss: yes
          plugin_rss_source: https://doany.io/feed.xml
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561199164371500"
